// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVJl7VJpLrLKbVXMo8hAzZcC1fxstOfC0',
    appId: '1:116177928018:android:92939812d8cef2f1c1448b',
    messagingSenderId: '116177928018',
    projectId: 'spacademy-e3371',
    storageBucket: 'spacademy-e3371.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcdyQECluSyUoqtACcijt0Qz6nTKqs2hM',
    appId: '1:116177928018:ios:83553be67f639b99c1448b',
    messagingSenderId: '116177928018',
    projectId: 'spacademy-e3371',
    storageBucket: 'spacademy-e3371.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbnLP0VgYQpUNJoO7iv3-A6I3J1ZJjnj4',
    appId: '1:116177928018:web:454a9bf1dbe0562cc1448b',
    messagingSenderId: '116177928018',
    projectId: 'spacademy-e3371',
    authDomain: 'spacademy-e3371.firebaseapp.com',
    storageBucket: 'spacademy-e3371.firebasestorage.app',
    measurementId: 'G-PLCJVGZCZ9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcdyQECluSyUoqtACcijt0Qz6nTKqs2hM',
    appId: '1:116177928018:ios:83553be67f639b99c1448b',
    messagingSenderId: '116177928018',
    projectId: 'spacademy-e3371',
    storageBucket: 'spacademy-e3371.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbnLP0VgYQpUNJoO7iv3-A6I3J1ZJjnj4',
    appId: '1:116177928018:web:6509ab3b65ab272bc1448b',
    messagingSenderId: '116177928018',
    projectId: 'spacademy-e3371',
    authDomain: 'spacademy-e3371.firebaseapp.com',
    storageBucket: 'spacademy-e3371.firebasestorage.app',
    measurementId: 'G-KY0CFKJQNP',
  );
}
